USER_NAME="mybtc"
RPC_PASSWORD="bitcoin"

BITCOIN_VERSION="28.1"
BITCOIN_ARCH="x86_64-linux-gnu"

FULCRUM_VERSION="1.9.1"
FULCRUM_ARCH="x86_64-linux"
FULCRUM_DIR="/home/${USER_NAME}/fulcrum"
FULCRUM_DATA_DIR="${FULCRUM_DIR}/data"
FULCRUM_CONF_DIR="${FULCRUM_DIR}/config"
FULCRUM_SSL_DIR="${FULCRUM_DIR}/ssl"

